### ISSUE TITLE
Head symbolic version for the most recent version of a file name

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/kurjun#126]
When we have many versions of a file in the system we cannot get the most recent one easily. It would be nice to specify a version along with the file name when getting it's ID. If this version parameter is HEAD then it pulls the most recent.

**Comment by kylycht** [comment]
REST end point for templates already supports versions.
If version is specified it returns artifact with matching version, if such artifact does not exist null is returned.
If version is not specified it sorts(lexicographically) artifacts with matching name(since lookup is done by name) and returns the artifact.
Default value(which is null) can be treated as HEAD
